name = "betelino-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Schimbă această linie din .open-next în:
pages_build_output_dir = ".open-next/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "betelino-db"
database_id = "12909816-6996-4911-bfaf-793f1f9ce01f"
migrations_dir = "drizzle/migrations"