name = "betelino"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Linia salvatoare pentru Cloudflare Pages (înlocuiește parametrul "main"):
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "betelino-db"
database_id = "12909816-6996-4911-bfaf-793f1f9ce01f"
migrations_dir = "drizzle/migrations"# force pipeline redeploy
