name = "betelino"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[[d1_databases]]
binding = "DB"
database_name = "betelino-db"
database_id = "12909816-6996-4911-bfaf-793f1f9ce01f"
migrations_dir = "drizzle/migrations"
